### ISSUE TITLE
Installation on / , go to ecrire => Site en travaux

### ISSUE THREAD

**Issue by Shnoulle** [magikcypress/spip_ynh#1]
Hi,

Surely because i try to install an example.org/ , but, just after install:
Goes to / : 403 error
Goes to /index.php : File not found
Goes to /ecrire/ : Site en travaux

I have this in error:
````
2015/11/06 12:33:03 [error] 30369#0: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.0.254, server: expample.net, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-spip.sock:", host: "bdx.shnoulle.net"
````

**Comment by magikcypress** [comment]
Hello,

Normally, this script install source code into spip sub-directory example.org/spip/ecrire, not example.org/ecrire

Regards,

**Comment by Shnoulle** [comment]
Yes, but i set / (homedir) for base url : this is allowed when installing. And then it broke. ANd if user want example.or/web/ or anything else ?

**Comment by magikcypress** [comment]
If you change chdir options in php-fpm.conf is ok ? But it's possible to change line 74 into the install script.
