### ISSUE TITLE
Update app package regarding YunoHost 2.4 changes

### ISSUE THREAD

**Issue by jeromelebleu** [magikcypress/spip_ynh#3]
You should consider to update your app package and scripts to integrate YunoHost changes introduced by v2.4 to make it works on this new stable version - and the following! Currently, as you defined the app as a _multi-instances_ one, it will not install on v2.4+ until any update.

For notes, documentation and example about those changes, you can refer to:
- YunoHost 2.4 announcement: https://forum.yunohost.org/t/yunohost-2-4-released/
- Changes in app packaging: https://forum.yunohost.org/t/news-about-app-management-and-packaging-in-yunohost-2-4/
- Example app: https://github.com/YunoHost/example_ynh

Also, if you don't have time or need help, do not hesitate, I can contribute if you want!

Thanks for you app anyway! :)

**Comment by genma** [comment]
Can I help for this issue too? I need it ;-)

**Comment by magikcypress** [comment]
I updated, but I do not know if it is correct ?

**Comment by jeromelebleu** [comment]
@magikcypress thanks, but it's unfortunately not sufficient.

As explained, the way multi-instances apps are managed has changed with non-backward compatibility. You now have to take care of that in your scripts, it's not dirtily replaced by yunohost anymore. It means that the second *spip_ynh* you will install will break everything regarding you last commit - as you've updated the `manifest.json` but not your scripts.

You can refer to the [example app](https://github.com/YunoHost/example_ynh) if you want an implementation example. And again, feel free to ask if I can help! :)

**Comment by magikcypress** [comment]
@jeromelebleu It's ok for you ? ;)

**Comment by magikcypress** [comment]
Close issue
